# Generated by Django 6.0.5 on 2026-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaidRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('maid', 'Maid / House Help'), ('cook', 'Cook / Chef'), ('nanny', 'Nanny / Babysitter'), ('caregiver', 'Caregiver'), ('driver', 'Driver')], max_length=20)),
                ('work_type', models.CharField(choices=[('live_in', 'Live-in'), ('live_out', 'Live-out'), ('both', 'Live-in or Live-out')], max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField()),
                ('availability', models.CharField(max_length=100)),
                ('expected_salary', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('bio', models.TextField()),
                ('nin', models.CharField(max_length=11)),
                ('reference_name', models.CharField(max_length=120)),
                ('reference_phone', models.CharField(max_length=30)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='maid_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
