# Generated by Django 6.1 on 2026-08-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0004_seed_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in URL tab ID, e.g. "maid"', max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('badge_label', models.CharField(blank=True, max_length=60)),
                ('badge_color', models.CharField(choices=[('blue', 'Blue — Most Popular'), ('orange', 'Orange — In Demand'), ('green', 'Green — Highly Rated'), ('purple', 'Purple — Compassionate'), ('teal', 'Teal')], default='blue', max_length=20)),
                ('icon', models.CharField(choices=[('fa-broom', 'Broom (Maid)'), ('fa-utensils', 'Utensils (Cook)'), ('fa-baby', 'Baby (Nanny)'), ('fa-heart-pulse', 'Heart Pulse (Elderly Care)'), ('fa-car', 'Car (Driver)'), ('fa-star', 'Star (Generic)')], default='fa-star', max_length=40)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='One feature per line')),
                ('image_url', models.URLField(blank=True)),
                ('available_count', models.CharField(default='0+', max_length=20)),
                ('avg_rating', models.CharField(default='4.9★', max_length=10)),
                ('guarantee_days', models.PositiveSmallIntegerField(default=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
