# Generated by Django 6.1 on 2026-08-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0006_seed_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(help_text='Short summary shown on the listing page')),
                ('category', models.CharField(choices=[('hiring', 'Hiring Tips'), ('safety', 'Safety'), ('career', 'Career Advice'), ('family', 'Family Life'), ('guides', 'How-To Guides'), ('general', 'General')], default='general', max_length=20)),
                ('author_name', models.CharField(max_length=120)),
                ('author_avatar', models.URLField(blank=True, help_text='URL to author profile photo')),
                ('author_bio', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('content', models.TextField(help_text='Full article HTML or plain text')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('read_time', models.PositiveSmallIntegerField(default=5, help_text='Estimated read time in minutes')),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
