# Generated by Django 6.1 on 2026-08-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0008_seed_blogposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_file',
            field=models.ImageField(blank=True, help_text='Upload a cover image (used instead of URL if provided)', null=True, upload_to='blog/covers/'),
        ),
    ]
