# Generated by Django 6.1 on 2026-08-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0010_reseed_blogposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(help_text='Original DB id', unique=True)),
                ('reg_number', models.CharField(help_text='e.g. SRM-1658', max_length=20)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('photo_filename', models.CharField(blank=True, help_text='Filename as stored on old server', max_length=300)),
                ('assign_status', models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Available')], default='unassigned', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
