# Generated by Django 6.1 on 2026-08-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0012_seed_maidprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a profile photo', null=True, upload_to='maid_profiles/'),
        ),
    ]
