# Generated by Django 6.1 on 2026-08-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0014_supportmessage_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
