# Generated by Django 6.1 on 2026-08-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0015_supportmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
