# Generated by Django 6.0.5 on 2026-08-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0017_placementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementrequest',
            name='replacement_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='MaidApp.placementrequest'),
        ),
    ]
