# Generated by Django 6.0.5 on 2026-08-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0018_placementrequest_replacement_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
