# Generated by Django 6.1 on 2026-08-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0021_urlfield_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maidprofile',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
