# Generated by Django 6.1 on 2026-08-25 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0022_alter_maidprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from admin')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maid_recommendations', to=settings.AUTH_USER_MODEL)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='MaidApp.maidprofile')),
                ('recommended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommended_at'],
                'unique_together': {('employer', 'maid')},
            },
        ),
    ]
