# Generated by Django 6.1 on 2026-08-27 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0023_maidrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveIntegerField(help_text='Original `request.id` from the legacy database', unique=True)),
                ('first_name', models.CharField(blank=True, max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('home_address', models.CharField(blank=True, max_length=500)),
                ('profession', models.CharField(blank=True, max_length=500)),
                ('company', models.CharField(blank=True, max_length=500)),
                ('company_address', models.CharField(blank=True, max_length=500)),
                ('family_members', models.CharField(blank=True, max_length=500)),
                ('apartment_type', models.CharField(blank=True, max_length=500)),
                ('marital_status', models.CharField(blank=True, max_length=500)),
                ('maid_gender', models.CharField(blank=True, max_length=500)),
                ('requested_service', models.TextField(blank=True)),
                ('how_soon', models.CharField(blank=True, max_length=500)),
                ('plan', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='premium', max_length=20)),
                ('assigned', models.CharField(blank=True, help_text="Raw legacy 'assigned' value ('unassigned' or a maid reg number)", max_length=500)),
                ('is_spam', models.BooleanField(db_index=True, default=False, help_text='Bot/spam submission detected during import')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legacy employer (request.sql)',
                'verbose_name_plural': 'Legacy employers (request.sql)',
                'ordering': ['legacy_id'],
            },
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='assigned_employer',
            field=models.ForeignKey(blank=True, help_text='Site employer this maid is currently placed with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='assigned_legacy_employer',
            field=models.ForeignKey(blank=True, help_text='Legacy employer (request.sql) this maid is currently placed with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maids', to='MaidApp.legacyemployer'),
        ),
    ]
