# Generated by Django 6.1 on 2026-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0024_legacyemployer_maidprofile_assigned_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditablePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content rendered on the public page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
