# Generated by Django 6.1 on 2026-08-30 16:53

from django.db import migrations, models


def dedupe_pending_registrations(apps, schema_editor):
    """Remove duplicated maid applications before applying the NIN uniqueness
    constraint. When the same NIN appears more than once (a double-submitted or
    retried form), keep only the most recent submission."""
    MaidRegistration = apps.get_model('MaidApp', 'MaidRegistration')
    duplicates = (
        MaidRegistration.objects
        .values('nin')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )
    for row in duplicates:
        keep = MaidRegistration.objects.filter(nin=row['nin']).order_by('-id').first()
        if keep is not None:
            MaidRegistration.objects.filter(nin=row['nin']).exclude(pk=keep.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('MaidApp', '0026_editablepage_hero_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablepage',
            name='hero_pill',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RunPython(dedupe_pending_registrations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='maidregistration',
            name='nin',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
