# Generated by Django 6.1 on 2026-08-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_pendingsignup_flw_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='request_details',
            field=models.TextField(blank=True, help_text="Employer's specific requirements and requests"),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='request_details',
            field=models.TextField(blank=True, help_text="Employer's specific requirements and requests"),
        ),
    ]
