# Generated by Django 6.1 on 2026-09-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_employerprofile_request_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='apartment_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='expected_resume_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='house_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='maid_gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='rooms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='apartment_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='expected_resume_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='house_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='maid_gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='marital_status',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='profession',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='rooms',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
